# Generated by Django 4.1 on 2022-09-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='fichier',
            new_name='file',
        ),
    ]
